when:
  - event: push
    branch: ros2

steps:
  - name: Prepare sysroot
    image: ros:humble-ros-base-jammy
    commands:
      - cd alfred
      - rm -fR src/sim/
      - . /opt/ros/$ROS_DISTRO/setup.sh
      - apt-get update
      - apt-get install -y symlinks
      - rosdep install -y
        --from-paths src
        --ignore-src
      - cd /
      - symlinks -rc .
      - mkdir -p $CI_WORKSPACE/alfred/cross_compile/sysroot
      - cp -a lib usr opt etc $CI_WORKSPACE/alfred/cross_compile/sysroot

  - name: Build Alfred
    image: ros:humble-ros-base-jammy
    environment:
      RMW_IMPLEMENTATION: rmw_fastrtps_cpp
      TARGET_ARCH: aarch64
      CROSS_COMPILE: /usr/bin/aarch64-linux-gnu-
      PYTHON_SOABI: cpython-310-aarch64-linux-gnu
      CC: /usr/bin/aarch64-linux-gnu-gcc
      CXX: /usr/bin/aarch64-linux-gnu-g++

    commands:
      - export SYSROOT=$CI_WORKSPACE/alfred/cross_compile/sysroot
      - export ROS2_INSTALL_PATH=$CI_WORKSPACE/alfred/install
      - export CROSS_COMPILE_DIR=$CI_WORKSPACE/alfred/cross_compile
      - cd alfred
      - rm -fR sim/
      - . /opt/ros/$ROS_DISTRO/setup.sh
      - apt-get update
      - apt-get install -y g++-aarch64-linux-gnu g++-arm-linux-gnueabihf
      - rosdep install -y
        --from-paths src
        --ignore-src
      # Quick and dirty fix => to be investigated further
      - cp $SYSROOT/usr/lib/aarch64-linux-gnu/libpython3.10.so /usr/lib/aarch64-linux-gnu/libpython3.10.so
      - colcon build
        --cmake-args -DCMAKE_TOOLCHAIN_FILE=$CROSS_COMPILE_DIR/cmake-toolchains/generic_linux.cmake
        --no-warn-unused-cli
    depends_on:
      - Prepare sysroot

  - name: Copy install files to host
    image: alpine:latest
    commands:
      - apk update && apk add rsync
      - rsync -a --delete $CI_WORKSPACE/alfred/install/ /tmp/target_files/
    depends_on:
      - Build Alfred
    volumes:
      - /usr/tmp/install:/tmp/target_files/

  - name: Archive Alfred's build logs
    image: alpine:latest
    commands:
      - cd alfred/log/latest_build/
      - find -type f -print | tar -czf build_logs.tar.gz --no-recursion -T -
    when:
      status: [failure]
    depends_on:
      - Build Alfred

  - name: Archive Alfred's binaries
    image: alpine:latest
    commands:
      - cd alfred/install/
      - find -print | tar -czf install.tar.gz --no-recursion -T -
    depends_on:
      - Copy install files to host

